"""
build_table_and_pareto_real.py — Real-data Table 8 + Pareto figure

Consumes:
    results/real/baseline_zscore_summary.json      (baseline_zscore_real.py)
    results/eal_real/eal_factorial_summary.json    (eal_factorial_real.py --native-min)
Writes:
    tables/real_data_real.tex
    figures/pareto_design_space_real.pdf|png
    results/table_pareto_manifest_real.json

Ordering emerges from the actual detector outputs on the real CIC-IDS2017
Friday-Afternoon DDoS file — any deviation from the proxy ordering is
reported as-is (empirical finding, no silent overwrite).
"""
from __future__ import annotations
import json
from pathlib import Path
import math
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

HERE = Path(__file__).resolve().parent
KIT  = HERE.parent
RES_BASE = KIT / "results" / "real" / "baseline_zscore_summary.json"
RES_EAL  = KIT / "results" / "eal_real" / "eal_factorial_summary.json"
TABLES_OUT = KIT / "tables" / "real_data_real.tex"
FIG_OUT_PDF = KIT / "figures" / "pareto_design_space_real.pdf"
FIG_OUT_PNG = KIT / "figures" / "pareto_design_space_real.png"
MANIFEST_OUT = KIT / "results" / "table_pareto_manifest_real.json"

TABLES_OUT.parent.mkdir(parents=True, exist_ok=True)
FIG_OUT_PDF.parent.mkdir(parents=True, exist_ok=True)

baseline = json.loads(RES_BASE.read_text())
eal = json.loads(RES_EAL.read_text())


def fmt_num(x, d=3):
    if x is None or (isinstance(x, float) and math.isnan(x)):
        return "--"
    if isinstance(x, float):
        return f"{x:.{d}f}"
    return str(x)


def fmt_delay(x):
    if x is None or (isinstance(x, float) and math.isnan(x)):
        return "miss"
    return f"{int(round(x))}\\,s"


# ---------------- LaTeX table ----------------
rows = [
    ("Baseline", "z-score / pkt-rate",     baseline["pktrate"]),
    ("Baseline", "z-score / byte-rate",    baseline["byterate"]),
    ("Baseline", "z-score / dport-entr.",  baseline["dportentropy"]),
]
eal_rows = [(f"EAL / {m['estimator']}({m['W']},{m['s']})", m) for m in eal]

tex = []
tex.append("% Auto-generated by build_table_and_pareto_real.py on the REAL CIC-IDS2017")
tex.append("% Friday-Afternoon DDoS file (TrafficLabelling variant, 225,711 flows,")
tex.append("% 93 unique minute-granularity timestamps, DDoS window 18:56--19:16 UTC).")
tex.append("% Baseline: per-minute aggregation with the same k=3 causal detector.")
tex.append("% EAL grid rescaled to native minute (W,s) in {(8,4),(16,2),(32,1)} across")
tex.append("% Shannon/Sample/Permutation estimators.  See CHANGELOG_REAL.md.")
tex.append("\\begin{tabular}{lrrrrrr}")
tex.append("\\toprule")
tex.append("Configuration & AUC$_\\text{ROC}$ & AUC$_\\text{PR}$ & FPR$_{\\!A}$ & Delay & Fires & Detected \\\\")
tex.append("\\midrule")
for kind, label, m in rows:
    tex.append(
        f"\\textit{{{label}}} & "
        f"{fmt_num(m['AUC_ROC'])} & {fmt_num(m['AUC_PR'])} & "
        f"{fmt_num(m['FPR_at_k3'])} & {fmt_delay(m['detection_delay_s'])} & "
        f"{m['n_fires_post_warmup']} & "
        f"{'yes' if m['detected'] else 'no'} \\\\"
    )
tex.append("\\midrule")
for label, m in eal_rows:
    tex.append(
        f"{label} & "
        f"{fmt_num(m['AUC_ROC'])} & {fmt_num(m['AUC_PR'])} & "
        f"{fmt_num(m['FPR_post_warmup'])} & {fmt_delay(m['detection_delay_s'])} & "
        f"{m['n_fires_post_warmup']} & "
        f"{'yes' if m['detected'] else 'no'} \\\\"
    )
tex.append("\\bottomrule")
tex.append("\\end{tabular}")
TABLES_OUT.write_text("\n".join(tex))
print(f"[table] wrote {TABLES_OUT}")

# ---------------- Pareto figure ----------------
points = []
for kind, label, m in rows:
    points.append({
        "kind": "baseline",
        "label": label.replace("z-score / ", "z/"),
        "fpr": m["FPR_at_k3"], "delay": m["detection_delay_s"],
        "detected": m["detected"],
        "auc_roc": m["AUC_ROC"],
    })
for label, m in eal_rows:
    points.append({
        "kind": "eal",
        "label": label.replace("EAL / ", ""),
        "fpr": m["FPR_post_warmup"], "delay": m["detection_delay_s"],
        "detected": m["detected"],
        "auc_roc": m["AUC_ROC"],
    })

detected_delays = [p["delay"] for p in points if p["detected"] and not (isinstance(p["delay"], float) and math.isnan(p["delay"]))]
miss_y = (max(detected_delays) + 250) if detected_delays else 1500.0

fig, ax = plt.subplots(figsize=(9.2, 5.4), dpi=150)
colors  = {"baseline": "#888", "eal": "#1f4e9c"}
markers = {"baseline": "s",     "eal": "o"}

# --- Detected points: annotate each with well-separated labels ---
# Only 3 detected points on real data → dodge labels along +/- offsets.
detected = [p for p in points if p["detected"]]
for idx, p in enumerate(detected):
    ax.scatter(p["fpr"], p["delay"], s=120, c=colors[p["kind"]], marker=markers[p["kind"]],
               edgecolors="black", linewidths=0.8, alpha=0.9, zorder=3)
    # Fixed offset per index so annotations never overlap
    dx = 0.008
    dy = 30 if idx % 2 == 0 else -55
    ax.annotate(p["label"], (p["fpr"], p["delay"]),
                xytext=(p["fpr"] + dx, p["delay"] + dy),
                fontsize=9, alpha=0.9, zorder=4)

# --- Missed points: single open marker in plot + list panel outside axes ---
missed = [p for p in points if not p["detected"]]
if missed:
    ax.scatter(0.0, miss_y, s=140, c="white", marker="o", edgecolors="black", linewidths=1.0, zorder=3)
    labels_text = f"Missed cluster ({len(missed)} configs)\nAUC$_{{ROC}}$ shown, fires=0:\n\n" + \
                  "\n".join(f"\u2022 {p['label']}  (AUC={p['auc_roc']:.3f})" for p in missed)
    # Place text box outside the plot area on the right
    fig.text(0.735, 0.52, labels_text, fontsize=7.5, color="#400",
             va="center", ha="left",
             bbox=dict(boxstyle="round,pad=0.4", facecolor="#fde", edgecolor="#c99", alpha=0.9))

# Pareto front (detected only, lower-left = better)
det = [p for p in points if p["detected"]]
det.sort(key=lambda p: (p["fpr"], p["delay"]))
pareto = []
best_delay = float("inf")
for p in det:
    if p["delay"] < best_delay:
        pareto.append(p); best_delay = p["delay"]
if len(pareto) >= 2:
    xs = [p["fpr"] for p in pareto]
    ys = [p["delay"] for p in pareto]
    ax.plot(xs, ys, "--", c="#444", alpha=0.55, zorder=2, lw=1.2,
            label="Pareto front (across all configurations)")

ax.axhspan(miss_y - 60, miss_y + 60, facecolor="#fde", alpha=0.35, zorder=1)
ax.text(0.014, miss_y + 95, "miss region",
        fontsize=8, style="italic", color="#a33", ha="left")

ax.set_xlabel("FPR$_{\\!A}$ (post-warmup, pre-attack benign)", fontsize=10)
ax.set_ylabel("Detection delay (s)", fontsize=10)
ax.set_title("Design-space Pareto front on REAL CIC-IDS2017 Friday-Afternoon DDoS\n"
             "(circles: EAL configs, native-min grid; squares: z-score baseline; open circle: missed cluster)",
             fontsize=9.5)
ax.set_ylim(-120, miss_y + 200)
ax.set_xlim(-0.005, 0.20)
ax.grid(True, ls=":", alpha=0.4)
if len(pareto) >= 2:
    ax.legend(loc="lower right", fontsize=8)
plt.tight_layout(rect=(0, 0, 0.72, 1))
plt.savefig(FIG_OUT_PDF)
plt.savefig(FIG_OUT_PNG)
print(f"[fig] wrote {FIG_OUT_PDF}")
print(f"[fig] wrote {FIG_OUT_PNG}")

manifest = {
    "source_dataset": "CIC-IDS2017 TrafficLabelling / Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv",
    "n_baseline": len(rows),
    "n_eal": len(eal_rows),
    "n_total_points": len(points),
    "n_detected": sum(1 for p in points if p["detected"]),
    "n_missed": sum(1 for p in points if not p["detected"]),
    "pareto_front": [
        {"label": p["label"], "fpr": p["fpr"], "delay": p["delay"], "kind": p["kind"], "auc_roc": p["auc_roc"]}
        for p in pareto
    ],
    "notes": [
        "Real-data granularity is per-minute (see CHANGELOG_REAL.md).",
        "Original (W,s) grid produced 0 detections; native-minute rescaled grid used instead.",
        "AUC_ROC reported for all EAL configs even when the fixed tau leaves fires=0."
    ],
}
MANIFEST_OUT.write_text(json.dumps(manifest, indent=2, default=str))
print(json.dumps(manifest, indent=2, default=str))
