"""
build_table_and_pareto.py — Build LaTeX Table 8 + Pareto figure
from baseline + EAL JSON summaries.
"""

from __future__ import annotations
import json
import argparse
from pathlib import Path
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

parser = argparse.ArgumentParser()
parser.add_argument("--baseline", type=str, required=True)
parser.add_argument("--eal", type=str, required=True)
parser.add_argument("--tex", type=str, required=True)
parser.add_argument("--fig", type=str, required=True)
args = parser.parse_args()

TABLES_OUT = Path(args.tex)
FIG_OUT_PDF = Path(f"{args.fig}.pdf")
FIG_OUT_PNG = Path(f"{args.fig}.png")

TABLES_OUT.parent.mkdir(parents=True, exist_ok=True)
FIG_OUT_PDF.parent.mkdir(parents=True, exist_ok=True)

baseline = json.loads(Path(args.baseline).read_text())
eal = json.loads(Path(args.eal).read_text())


def fmt_num(x, d=3):
    if x is None or (isinstance(x, float) and (x != x)):
        return "--"
    if isinstance(x, float):
        return f"{x:.{d}f}"
    return str(x)


def fmt_delay(x):
    if x is None or (isinstance(x, float) and (x != x)):
        return "miss"
    return f"{int(round(x))}\\,s"


# ---------------- LaTeX Table ----------------
rows = []
B = baseline
rows.append(("Baseline", "z-score / pkt-rate", B["pktrate"]))
rows.append(("Baseline", "z-score / byte-rate", B["byterate"]))
rows.append(("Baseline", "z-score / dport-entr.", B["dportentropy"]))

eal_rows = []
for m in eal:
    label = f"EAL / {m['estimator']}({m['W']},{m['s']})"
    eal_rows.append((label, m))

tex = []
tex.append("% Auto-generated by build_table_and_pareto.py from real run JSONs.")
tex.append("% Source: results/proxy and results/eal (DAV-IDE/paper4-esorics repo layout).")
tex.append(
    "% CIC-IDS2017-aligned proxy stream, seed=20260606, 4h afternoon, 246k flows,"
)
tex.append("% attack core window 15:55--16:15, residual elevated to 17:00.")
tex.append(
    "% AUC caveat: AUC_ROC / AUC_PR are computed by scikit-learn on this targeted subset;"
)
tex.append(
    "% they are diagnostic of the transparent statistical baseline and the proxy EAL pipeline"
)
tex.append(
    "% on a single scenario, NOT a detection-performance claim of Paper 4. The inherited"
)
tex.append(
    "% AUC~0.993 / FPR~0.021 of Paper 3 (NTP amplification scenario) is not superseded here."
)
tex.append("\\begin{tabular}{lrrrrrr}")
tex.append("\\toprule")
tex.append(
    "Configuration & AUC$_\\text{ROC}$ & AUC$_\\text{PR}$ & FPR$_{\\!A}$ & Delay & Fires & Detected \\\\"
)
tex.append("\\midrule")

# Baselines
for kind, label, m in rows:
    tex.append(
        f"\\textit{{{label}}} & "
        f"{fmt_num(m['AUC_ROC'])} & {fmt_num(m['AUC_PR'])} & "
        f"{fmt_num(m['FPR_at_k3'])} & {fmt_delay(m['detection_delay_s'])} & "
        f"{m['n_fires_post_warmup']} & "
        f"{'yes' if m['detected'] else 'no'} \\\\"
    )
tex.append("\\midrule")

# EAL configurations
for label, m in eal_rows:
    tex.append(
        f"{label} & "
        f"{fmt_num(m['AUC_ROC'])} & {fmt_num(m['AUC_PR'])} & "
        f"{fmt_num(m['FPR_post_warmup'])} & {fmt_delay(m['detection_delay_s'])} & "
        f"{m['n_fires_post_warmup']} & "
        f"{'yes' if m['detected'] else 'no'} \\\\"
    )

tex.append("\\bottomrule")
tex.append("\\end{tabular}")
TABLES_OUT.write_text("\n".join(tex))
print(f"[table] wrote {TABLES_OUT}")

# ---------------- Pareto figure ----------------
points = []
# baseline
for kind, label, m in rows:
    points.append(
        {
            "kind": "baseline",
            "label": label.replace("z-score / ", "z/"),
            "fpr": m["FPR_at_k3"],
            "delay": m["detection_delay_s"],
            "detected": m["detected"],
        }
    )
# eal
for label, m in eal_rows:
    points.append(
        {
            "kind": "eal",
            "label": label.replace("EAL / ", ""),
            "fpr": m["FPR_post_warmup"],
            "delay": m["detection_delay_s"],
            "detected": m["detected"],
        }
    )

# Determine where to plot "miss" points
detected_delays = [p["delay"] for p in points if p["detected"]]
miss_y = (max(detected_delays) + 250) if detected_delays else 1500.0

fig, ax = plt.subplots(figsize=(7.6, 5.2), dpi=150)
colors = {"baseline": "#888", "eal": "#1f4e9c"}
markers = {"baseline": "s", "eal": "o"}

# Plot detected points with individual labels
detected_pts = [p for p in points if p["detected"]]
used_label_positions = []
for p in detected_pts:
    ax.scatter(
        p["fpr"],
        p["delay"],
        s=110,
        c=colors[p["kind"]],
        marker=markers[p["kind"]],
        edgecolors="black",
        linewidths=0.8,
        alpha=0.9,
        zorder=3,
    )
    candidates = [
        (p["fpr"] + 0.004, p["delay"] + 30),
        (p["fpr"] + 0.004, p["delay"] - 50),
        (p["fpr"] - 0.022, p["delay"] + 30),
        (p["fpr"] - 0.022, p["delay"] - 50),
    ]
    chosen = candidates[0]
    for cx, cy in candidates:
        if all(
            abs(cx - ux) > 0.012 or abs(cy - uy) > 50 for ux, uy in used_label_positions
        ):
            chosen = (cx, cy)
            break
    used_label_positions.append(chosen)
    ax.annotate(
        p["label"],
        (p["fpr"], p["delay"]),
        xytext=chosen,
        fontsize=8,
        alpha=0.9,
        zorder=4,
    )

# Plot missed points as a single cluster
missed = [p for p in points if not p["detected"]]
if missed:
    ax.scatter(
        0.0,
        miss_y,
        s=120,
        c="white",
        marker="o",
        edgecolors="black",
        linewidths=1.0,
        zorder=3,
    )
    lines = []
    for i in range(0, len(missed), 2):
        chunk = missed[i : i + 2]
        lines.append(", ".join(p["label"] for p in chunk))
    labels_text = f"missed ({len(missed)} configs):\n" + "\n".join(lines)
    ax.annotate(
        labels_text,
        (0.0, miss_y),
        xytext=(0.030, miss_y - 30),
        fontsize=7.0,
        alpha=0.9,
        zorder=4,
        color="#600",
        arrowprops=dict(arrowstyle="-", lw=0.5, color="#999"),
        va="center",
    )

# Pareto front
det = [p for p in points if p["detected"]]
det.sort(key=lambda p: (p["fpr"], p["delay"]))
pareto = []
best_delay = float("inf")
for p in det:
    if p["delay"] < best_delay:
        pareto.append(p)
        best_delay = p["delay"]
if len(pareto) >= 2:
    xs = [p["fpr"] for p in pareto]
    ys = [p["delay"] for p in pareto]
    ax.plot(
        xs,
        ys,
        "--",
        c="#444",
        alpha=0.55,
        zorder=2,
        lw=1.2,
        label="Pareto front (across all configurations)",
    )

# Miss-region shading band
ax.axhspan(miss_y - 60, miss_y + 60, facecolor="#fde", alpha=0.35, zorder=1)
ax.text(
    0.155,
    miss_y - 90,
    "miss region (no fire $\\geq$ first attack second)",
    fontsize=7,
    style="italic",
    color="#a33",
    ha="right",
)

ax.set_xlabel("FPR$_{\\!A}$ (post-warmup, pre-attack benign)", fontsize=10)
ax.set_ylabel("Detection delay (s)", fontsize=10)
ax.set_title(
    "Design-space Pareto front on CIC-IDS2017-aligned proxy stream\n"
    "(circles: EAL configurations; squares: z-score baseline; "
    "open circle: missed cluster)",
    fontsize=9.5,
)
ax.set_ylim(-120, miss_y + 200)
ax.set_xlim(-0.005, 0.20)
ax.grid(True, ls=":", alpha=0.4)
ax.legend(loc="lower right", fontsize=8)
plt.tight_layout()
plt.savefig(FIG_OUT_PDF)
plt.savefig(FIG_OUT_PNG)
print(f"[fig] wrote {FIG_OUT_PDF}")
print(f"[fig] wrote {FIG_OUT_PNG}")

# Side info dump (scrive in RES usando il path assoluto fornito dal parser)
manifest = {
    "n_baseline": len(rows),
    "n_eal": len(eal_rows),
    "n_total_points": len(points),
    "n_detected": sum(1 for p in points if p["detected"]),
    "n_missed": sum(1 for p in points if not p["detected"]),
    "pareto_front": [
        {"label": p["label"], "fpr": p["fpr"], "delay": p["delay"], "kind": p["kind"]}
        for p in pareto
    ],
}
manifest_out = Path(args.baseline).parent.parent / "table_pareto_manifest.json"
manifest_out.write_text(json.dumps(manifest, indent=2))
print(json.dumps(manifest, indent=2))
